# Generated by Django 4.2.2 on 2023-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='to_check',
            field=models.CharField(choices=[('occupied', 'OCCUPIED'), ('Free', 'FREE')], default='Free', max_length=100),
        ),
    ]
