# Generated by Django 4.2.2 on 2023-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machine_to_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='to_check',
        ),
        migrations.AddField(
            model_name='machine',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
