# Generated by Django 4.2.2 on 2023-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_notepad'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='nz_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='nz_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
