# Generated by Django 4.2.2 on 2023-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_machine_nz_end_time_machine_nz_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
