# Generated by Django 4.2.2 on 2024-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_booking_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='blooked',
            field=models.BooleanField(default=False),
        ),
    ]
